#!/usr/bin/env bash

cs3110 compile test_interp.ml &&
    for file in tests/*.ml; do
        echo "******* STARTING $file *******";
        cs3110 run test_interp.ml $file &&
        echo "******* ENDING $file *******";
    done
