#!/usr/bin/env bash

declare -a sources=(controller.ml interpreter.ml oBuffer.ml file.ml utils.ml main.ml key.ml)
for file in "${sources[@]}"; do
    if ! cs3110 compile $file ; then
        exit 1;
    fi;
done;

cs3110 compile test_interp.ml &&
    for file in tests/interpreter/*.ml; do
        if ! cs3110 run test_interp.ml $file ; then
            echo "$file FAILED!";
        else
            echo "$file passed";
        fi
    done;
cs3110 compile test_key_of_string.ml && cs3110 run test_key_of_string.ml
